name: learn-github-actions
run-name: ${{ github.actor }} is Testing Branches101
on: [push]
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          git fetch --depth=1 origin "+refs/heads/*:refs/remotes/origin/*"
          echo "Branches in this repository:"
          git branch -a
          echo "Current branch:"
          git rev-parse --abbrev-ref HEAD